### PR TITLE
update dlang in .github/workflows/main.yml

### PR DESCRIPTION
**Pull request by mw66**
update dlang in .github/workflows/main.yml

https://github.com/py2many/py2many/issues/610

### CODE REVIEW

**Comment by adsharma** [comment]
The code looks good, but I can't merge it because of the conflicts.
Could you try rebasing like so:

```
git rebase -i origin/main
git push -f
```

**Comment by mw66** [comment]
Done, can you try again?

**Comment by adsharma** [comment]
Any reason not to use [this](https://github.com/dlang-community/setup-dlang) to cover mac and windows?

Also, could you honor `FOCUS` so if someone is trying to run CI for a different language, we don't pay the cost of pulling these packages?

**Comment by mw66** [comment]
Ahh, at this stage I think you know much more than I do on setting up github.

I'm a regular desktop D user, and only know very basic github.

Can you take over this PR from here?

**Comment by adsharma** [comment]
Sure. I'll give it a shot this weekend.
@jayvdb knows more about it than I do :)

**Pull request closed without merging**
