### PR TITLE
[dlang] Honor args.indent

### LINKED ISSUE #611: main.yaml: support running multiple FOCUS languages, preferably parametrized
- Create a variable context in settings 
- Use the context in main.yaml
- Allow running manual workflow with languages A, B and C (say comma separated)

@jayvdb is this something you can look into?

### PR DESCRIPTION
**Pull request by adsharma**
Fixes #611

### CODE REVIEW

**Comment by adsharma** [comment]
@mw66: bubble_sort passes after this PR. We still have 9 failures which are not related to `indent_size`.

**Comment by mw66** [comment]
> @mw66: bubble_sort passes after this PR. We still have 9 failures which are not related to `indent_size`.

Where is log I can check these failures?

**Comment by adsharma** [comment]
Here: https://github.com/py2many/py2many/actions/runs/10238730915/job/28323473459

You can navigate via: Actions -> CI (main.yaml) and then look for a recent manual run targeting dlang.

**Comment by mw66** [comment]
How to keep the generated test file for debug?

I have set: `KEEP_EXISTING=1`

```
$ export KEEP_EXISTING=1
$ echo $KEEP_EXISTING
1
$ tox -- -k dlang

...

# but the generated file cannot be found:
$ find . -name dict_keys_explicit.d
```

Thanks.

**Comment by adsharma** [comment]
@mw66 I think it's called `KEEP_GENERATED`

**Comment by mw66** [comment]
OK.

In tests/test_unsupported.py
```
    "dict_keys_explicit": "{1: 1}.keys()",  
```

For Dart, this is translated to

```
$ cat ./tests/build/dict_keys_explicit.dart 
 main(List<String> argv) {
{1 : 1}.keys();}
```

For D, this is translated to
```
$ cat ./tests/build/dict_keys_explicit.d
[1: 1].keys();
```

Basically, the method wrapper `main()` is missing, so I'm just wondering where is the logic to add such method wrapper?

I `grep`-ed a bit, but didn't find the place. Can you let me know where to add this for D?

Thanks.

**Comment by mw66** [comment]
Never mind, found it here:

https://github.com/py2many/py2many/blob/6349cbd1074df08e121fe237b34dbefdd84be66d/tests/test_unsupported.py#L218

```
    if ext in [".dart", ".kt", ".rs", ".d"] and not is_script:
```

**Pull request merged**
