### PR TITLE
PyJL Transpiler extensions

### PR DESCRIPTION
**Pull request by MiguelMarcelino**
- Added PyJL transpiler features. Access`README` file in the `pyjl` folder for more information. 
- More extensive tests suite for Py2Many.

### CODE REVIEW

**Comment by div72** [comment]
Greetings!

First of all thank you for your contribution, a PR this big must have been a lot of effort to make. But as it currently stands(a 200+ commit and 400+ file diff PR) this is currently a reviewing nightmare. Could you cleanup the commits and maybe even split this into multiple PRs?

Also after a little peek, I noticed that you changed the permissions of text files to include execute. Why?

**Comment by MiguelMarcelino** [comment]
> Greetings!
> 
> First of all thank you for your contribution, a PR this big must have been a lot of effort to make. But as it currently stands(a 200+ commit and 400+ file diff PR) this is currently a reviewing nightmare. Could you cleanup the commits and maybe even split this into multiple PRs?
> 
> Also after a little peek, I noticed that you changed the permissions of text files to include execute. Why?

Hi there!
Yes, I could do that. The permission changes must have been a mistake on my part. I will try another pull request in a few days. Thank you for the quick reply!

**Comment by jayvdb** [comment]
Hi @MiguelMarcelino, you have a lot of changes here.  It would be helpful if you can create some smaller PRs with some of the features here, so we can get them in before we tackle this larger PyJL feature PR.

**Comment by jayvdb** [comment]
Note I've fixed CI in https://github.com/adsharma/py2many/pull/463 ; hopefully we'll get that merged soon so your PRs can be green

**Comment by MiguelMarcelino** [comment]
> Note I've fixed CI in https://github.com/adsharma/py2many/pull/463 ; hopefully we'll get that merged soon so your PRs can be green

Hi there! 
I am currently fixing some bugs in the transpiler. After I fix them, I will try to split the work into multiple pull requests. I will also merge your changes before I do so.
Thank you for all the help.
Miguel

**Pull request closed without merging**
