### PR TITLE
add method main wrapper for dlang in tests/test_unsupported.py

### PR DESCRIPTION
**Pull request by mw66**
https://github.com/py2many/py2many/pull/617#issuecomment-2282311927

### CODE REVIEW

**Comment by mw66** [comment]
@adsharma 

I tried to update the `tests/expected/` files, e.g. `tests/expected/infer_ops.d`, however it's not updated:

```
$ export UPDATE_EXPECTED=1
$ echo $UPDATE_EXPECTED
1
$ pytest-3 -k dlang -v
...

$ git status tests/expected/infer_ops.d
On branch dlang_fix
Your branch is up to date with 'origin/dlang_fix'.

nothing to commit, working tree clean
```

I noticed: the newly generated file is in: `./tests/build/infer_ops.d`, show I move them manually to `./tests/expected/infer_ops.d`?

Or it should be automatically updated?

If manually, I will update the https://github.com/py2many/py2many/blob/main/CONTRIBUTING.md with this info.

**Comment by adsharma** [comment]
Picked up one commit from this PR in #621 
Running CI here: https://github.com/py2many/py2many/actions/runs/10335974755

**Comment by mw66** [comment]
@adsharma fixed most failures.

BTW, how to mark some test files failure are expected (for the time being)? e.g.

https://github.com/py2many/py2many/blob/main/tests/cases/fib_with_argparse.py

https://github.com/py2many/py2many/blob/6349cbd1074df08e121fe237b34dbefdd84be66d/tests/cases/fib_with_argparse.py#L19C1-L20C1

This `Options.parse_args()` need special handling before can be compiled in Dlang.

**Comment by adsharma** [comment]
Could you rebase against main? Some commits from this PR have already landed.

**Comment by mw66** [comment]
> Could you rebase against main? Some commits from this PR have already landed.

I have to admit I'm a git novice, only know very few basic git commands.

Can you tell me the exact command?

Thanks.

**Comment by adsharma** [comment]
May be easier for me to create a new PR with your commits. Give me a few minutes.

**Comment by adsharma** [comment]
Merged via #623

**Pull request closed without merging**
